# Site settings
author: Thomas DiGregorio
title: Developer Talk
header-img: img/home-bg.png
email: digregoriothomas@yahoo.com
copyright_name: Thomas DiGregorio
description: > # this means to ignore newlines until "baseurl:"
  speaking code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ThomasDiGregor6
github_username:  ThomasDiGregorio

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
